name: 'Terraform'

on:
  workflow_dispatch:
    input:
      terraform_action:
        type: choice
        description: select terraform action
        options: 
          - apply
          - destroy
        required: true
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
     AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
     AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

    environment: Development

    steps: 
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.   - name: Terraform init
    - name: Terraform init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.3
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: '.'
        tf_actions_comment: true

    # Generates an execution plan for Terraform
    - name: Terraform plan
      uses: hashicorp/terraform-github-actions@master
      with:
         tf_actions_version: 0.14.3
         tf_actions_subcommand: 'plan'
         tf_actions_working_dir: '.'
         tf_actions_comment: true
   
    - name: Terraform apply
      if: ${{ github.events.inputs.terraform_action == 'apply' }}
      uses: hashicorp/terraform-github-actions@master
      with:
         tf_actions_version: 0.14.3
         tf_actions_subcommand: ${{ github.events.inputs.terraform_action}}
         tf_actions_working_dir: '.'
         tf_actions_comment: true  
         args: '-auto-approve -var="credentials.tfvars"'

    - name: Terraform destroy 
      if: ${{ github.events.inputs.terraform_action == 'destroy' }}
      uses: hashicorp/terraform-github-actions@master
      with:
         tf_actions_version: 0.14.3
         tf_actions_subcommand: ${{ github.events.inputs.terraform_action}}
         tf_actions_working_dir: '.'
         tf_actions_comment: true
         args: '-auto-approve -var="credentials.tfvars"'
